### ISSUE TITLE
obtener variables del json

### ISSUE THREAD

**Issue by abelnexus** [giansalex/peru-consult-api#10]
amigo intente obtener solo rasonsocial,ruc,direcion convirtiendo el json 
var_dump(json_decode($json));
var_dump(json_decode($json, true));

$company['razonSocial'];
$company['ruc'];
$company['direccion'];

pero no me convierte
Uncaught Error: Cannot use object of type Peru\Sunat\Company as array in

**Comment by abelnexus** [comment]
de esta manera si se puede
$company->ruc,,
$company->razonSocial,
$company->direccion

**Comment by giansalex** [comment]
Intenta de esta forma:
```php
$company = json_decode($json, true);
echo $company['ruc'];
```

**Comment by abelnexus** [comment]
no me permite. json_decode() expects parameter 1 to be string, object given in
 ni convirtiendolo a array me deja
$data[] = array($company);
$data['ruc'];
solo usandolo como objeto puedo obtener la variable

**Comment by giansalex** [comment]
estas usando el api o la libreria?, aunque si ya lo tienes en object, puedes usar directamente sus propiedades `$company->ruc`, no hay necesidad de conversion
