### ISSUE TITLE
direccion de personas naturales

### ISSUE THREAD

**Issue by abelnexus** [giansalex/peru-consult-api#11]
de todas las personas naturales con negocio (los que empiezan con ruc 10) siempre la direccion sale como : '-' esto es asi siempre o es algun fallo ?

**Comment by giansalex** [comment]
La consulta Ruc, accede a la pagina de consulta de sunat, alli tampoco aparece la direccion, fue quitada por temas de proteccion de los datos personales.
Puedes ver la noticia:
https://gestion.pe/economia/sunat-restringe-acceso-informacion-domicilio-fiscal-personas-naturales-229031
