### ISSUE TITLE
Mayores de edad recien cumplidos

### ISSUE THREAD

**Issue by byJuanjo** [giansalex/peru-consult-api#13]
Estimado GianCarlo, como te va tenia una duda, el dia de ayer me paso un caso peculiar, ya que en la busqueda de DNI puse un DNI de una persona que recien habia cumplido años en enero y aun no figuraban sus datos, el DNI es 70543071, y eso que ya contaba con el DNI azul fisico, alguna sugerencia?

**Comment by giansalex** [comment]
Hola @byJuanjo , debido a que Reniec cambio su pagina de consulta a una con recaptcha, ahora se usa el servicio de JNE. Lamentablemente no hay mucho que hacer. a menos que conozcas alguna otra pagina que se pueda extraer esa información.

**Comment by byJuanjo** [comment]
Gracias por la respuesta, investigare si encuentro algo te aviso.
