### ISSUE TITLE
JNE servicio caído

### ISSUE THREAD

**Issue by ajahuanex** [giansalex/peru-consult-api#14]
![Screenshot_2](https://user-images.githubusercontent.com/2767765/56057643-f3ae4100-5d24-11e9-9c69-d27e4877a64b.png)
Acaba de caer el servicio de consulta del JNE, o quiza sea temporal.

como error general sale "Slim Application Error"

**Comment by giansalex** [comment]
Actualmente el servicio esta activo. 😄
