### ISSUE TITLE
Jne DNI

### ISSUE THREAD

**Issue by jhenrygv** [giansalex/peru-consult-api#17]
Hola Gian, al actualizar vendor peru-consult con el último commit se corrige también aquí en el proyecto API. ?

**Comment by giansalex** [comment]
Hola @jhenrygv, primero tendre que generar un nuevo release, pero si lo quieres ahora, tendrias que cambiar la version en este repo de peru-consult a `dev-master` y actualizar con composer.

**Comment by giansalex** [comment]
Actualice el repositorio con la ultima versión
