### ISSUE TITLE
Habilitar CORS

### ISSUE THREAD

**Issue by OBSK** [giansalex/peru-consult-api#18]
Hola, @giansalex hay alguna forma de habilitar CORS, quiero hacer una solicitud y sale que están bloqueadas las solicitudes. Estoy intentando hacer un ajax.  Muchas gracias

**Comment by giansalex** [comment]
Hola @OBSK, por defecto cors esta habilitado para cualquier dominio, la configuración se encuentra en [middleware.php](https://github.com/giansalex/peru-consult-api/blob/master/src/middleware.php#L7).
Tal vez se estan enviando otros encabezados, podrias permitir cualquier cambiando
 a `'headers.allow' => ['*'],`

**Comment by OBSK** [comment]
Puse lo mismo que me dijiste, recibo este error:
`Access to XMLHttpRequest at 'http://consultas-app.herokuapp.com/api/v1/dni/72500947' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response..`

**Comment by OBSK** [comment]
`Access to XMLHttpRequest at 'http://consultas-app.herokuapp.com/api/v1/dni/72500947?token=abcxyz' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by giansalex** [comment]
@OBSK gracias por notificar esto, en la ultima actualización que permitía HTTP Requests asíncronos se perdieron los `headers` relacionados a CORS, pero ya se corrigió.
No necesitas cambiar la configuración, solo actualizar los últimos cambios del repositorio.

Fixed: 94bb74b361ba25cf8be8ceb08c84d1e20e6c62a2

**Comment by KhanMaytok** [comment]
Hola, el error de CORS se presenta nuevamente cuando hago una llamada desde javascript a la API. Intenté revisar el middleware.php que se muestra arriba, pero el archivo no se encuentra.

**Comment by giansalex** [comment]
Hola @KhanMaytok, es cierto, al cambiar de framework a Symfony, no se tuvo en cuenta eso, se tendrá que agregar [nelmio/cors-bundle](https://github.com/nelmio/NelmioCorsBundle).

**Comment by giansalex** [comment]
Si es solo para pruebas, pueden usar una [extension de Chrome](https://mybrowseraddon.com/access-control-allow-origin.html).
> Utilizar esta API desde el navegador expondría el token de seguridad, con lo cual otros podrian aprovecharse, las llamadas al API deberian hacerse desde un servidor.
