### ISSUE TITLE
Windows OS: The "reactphp.event_loop" service is synthetic

### ISSUE THREAD

**Issue by OD-n** [giansalex/peru-consult-api#20]
Buen dia, ¿alguien se topo con este error? me ocurrio al intentar hacer una consulta de DNI:

`The "reactphp.event_loop" service is synthetic, it needs to be set at boot time before it can be used.`
 
![image](https://user-images.githubusercontent.com/28074529/84304138-af335680-ab1d-11ea-8d9d-d2f5812bf348.png)

**Comment by giansalex** [comment]
Hola, con la ultima version han cambiado varias cosas, puedes seguir estos [pasos](https://github.com/giansalex/peru-consult-api#clonar-repositorio), o usar la versión anterior `git checkout 4.1`

**Comment by OD-n** [comment]
Quiza no es posible hacerlo con Windows, quisiera saber si tiene algo que ver.
El problema que tengo, es que estoy usando Windows y cuando deseo ejecutar: `composer install` me aparecen errores con "ext-pcntl", asi que para correrlo en Windows tuve que hacerlo con `composer install --ignore-platform-reqs`.

Luego de hacerlo e intentar ejecutar la linea `vendor/bin/server watch 0.0.0.0:8080 --adapter=App\\AppKernelAdapter` tengo el siguiente error: 
![image](https://user-images.githubusercontent.com/28074529/84318414-03493580-ab34-11ea-8260-825747a6a1a5.png)

**Comment by giansalex** [comment]
Si, es cierto según lo indicado en la [ultima version](https://github.com/giansalex/peru-consult-api/releases/tag/5.0), pero aquí hay un patch para que puedas ejecutarlo en windows.

Puedes descomprimir el archivo y ejecutar el comando:
```sh
git apply 0001-Allow-run-on-windows.patch
```

[0001-Allow-run-on-windows.zip](https://github.com/giansalex/peru-consult-api/files/4761513/0001-Allow-run-on-windows.zip)

**Comment by OD-n** [comment]
Hola @giansalex , disculpa que responda despues de tantos días, estaba usando una versión anterior y todo marchaba bien, pero ocurrio un error hace poco, asi que quise pobar con la ultima version, apliqué el patch y me aparecio esto: 
![image](https://user-images.githubusercontent.com/28074529/84574468-3d9d1780-ad6c-11ea-8123-9732f489cebf.png)

Usé el patch que me dejaste `0001-Allow-run-on-windows.zip`, gracias por las respuestas tan prontas por cierto

**Comment by giansalex** [comment]
Puedes usar este comando `git apply --ignore-space-change --ignore-whitespace 0001-Allow-run-on-windows.patch`

**Comment by OD-n** [comment]
Gracias por la respuesta @giansalex, me aparece algo extraño, según entiendo debería ignorarse los espacios en blanco, pero me aparece lo siguiente:
![image](https://user-images.githubusercontent.com/28074529/84575555-6d9be900-ad73-11ea-8911-0ef1cd800c96.png)
Que es practicamente los mismo, es que no estoy colocandolo bien?

**Comment by giansalex** [comment]
En mi caso no ocurre ese problema, he visto que hay varios posibles comandos que pueden corregirlo, podrías intentarlo; de todas formas agregare unos archivos para que se pueda ejecutar en windows sin tener que hacer eso.

**Comment by OD-n** [comment]
@giansalex te lo agradezco, de cualquier forma iré viendo por que pueden estar pasando estos errores; quizá tenga algo que ver con configuraciones mias
