### ISSUE TITLE
error consulta ruc

### ISSUE THREAD

**Issue by lengmiguel** [giansalex/peru-consult-api#27]
![imagen](https://user-images.githubusercontent.com/22181854/109332462-22a40200-782c-11eb-932e-b265051a9ba8.png)

**Comment by giansalex** [comment]
Podrias revisar en la carpeta  `var/log`, si hay algun archivo de log

**Comment by lengmiguel** [comment]
La url sigue funcionando pero cuando se hace la consulta del ruc en la pagina de sunat lo reenvia hacia otro sitio:

https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/frameCriterioBusqueda.jsp

![imagen](https://user-images.githubusercontent.com/22181854/109343046-bb417e80-783a-11eb-991c-eead0788e6a7.png)

**Comment by LuisFrank** [comment]
Me sucede lo mismo desde  ayer en la noche aproximadamente. Hoy continúa

**Comment by giansalex** [comment]
He notado cierta inestabilidad desde que insertaron recaptcha en sus paginas, si conocen de otras urls donde se puede obtener la misma información, podría ser una alternativa.

**Comment by giansalex** [comment]
@lengmiguel @LuisFrank se ha actualizado las urls en [peru-consult#36](https://github.com/giansalex/peru-consult/pull/36), parece que eso generaba inestabilidad.
