### ISSUE TITLE
api dni caido

### ISSUE THREAD

**Issue by elviss116** [giansalex/peru-consult-api#32]
hola, al hacer una solicitud para el din obtengo el siguiente error

{
    "$id": "1",
    "Message": "An error has occurred."
}

tengo el curl que facilitaron oar hacer la consulta a traves del jne y obtengo ese error

**Comment by giansalex** [comment]
Es un error en la pagina fuente: [JNE](https://aplicaciones007.jne.gob.pe/srop_publico/Consulta/PadronAfiliado)

**Comment by mario125** [comment]
a buscar una pronta solucion.

**Comment by elviss116** [comment]
muy aparte de esto, el ruc les funciona? nunca use el servicio del ruc , lo instale tal cual esta en la descripción y cuando consulto me sale bad request :  in src/Controller/RucController.php (line 41) , y otra duda es de no se donde debo sacar el token

**Comment by zahovicS** [comment]
> muy aparte de esto, el ruc les funciona? nunca use el servicio del ruc , lo instale tal cual esta en la descripción y cuando consulto me sale bad request : in src/Controller/RucController.php (line 41) , y otra duda es de no se donde debo sacar el token

a mi si me funciono el ruc, el token creo que está en el .env por defecto el token es: abcxyz

http://localhost/peru-consult-api/public/api/v1/ruc/20605498630?token=abcxyz

así dejé la ruta para hacer la consulta y me devuelve el json
y en el header puse el key:  
 'Accept' : 'application/json'

**Comment by elviss116** [comment]
> > muy aparte de esto, el ruc les funciona? nunca use el servicio del ruc , lo instale tal cual esta en la descripción y cuando consulto me sale bad request : in src/Controller/RucController.php (line 41) , y otra duda es de no se donde debo sacar el token
> 
> a mi si me funciono el ruc, el token creo que está en el .env por defecto el token es: abcxyz
> 
> http://localhost/peru-consult-api/public/api/v1/ruc/20605498630?token=abcxyz
> 
> así dejé la ruta para hacer la consulta y me devuelve el json
> y en el header puse el key:
> 'Accept' : 'application/json'

EL DNI ya se arreglo.


ya logre hacerlo correr lo del ruc, una pregunta, si quiera llevar esto a un hosting , cuales son los archivos php que debo subir al hosting?

**Comment by giansalex** [comment]
@elviss116 descarga el zip del ultimo [release](https://github.com/giansalex/peru-consult-api/archive/refs/tags/6.4.zip), descomprime e instala los paquetes.
```bash
composer install --no-dev
```
Luego todos esos archivos puedes subirlo al hosting.

**Comment by elviss116** [comment]
> @elviss116 descarga el zip del ultimo [release](https://github.com/giansalex/peru-consult-api/archive/refs/tags/6.4.zip), descomprime e instala los paquetes.
> 
> ```shell
> composer install --no-dev
> ```
> 
> Luego todos esos archivos puedes subirlo al hosting.

hola, hice eso, subi los archivos a un directorio del hosting llamado "api_ruc" que esta dentro de public_html, luego he creado un archivo php llamado "api.php" con el siguiente codigo y lo meti dentro del directorio donde estan todos los archivos q se descargaron luego de ejecutar el comando composer

require 'vendor/autoload.php';

$ruc = '10477981921';

$factory = new RucFactory();
$cs = $factory->create();

$company = $cs->get($ruc);
if (!$company) {
    echo 'Not found';
    return;
}

echo json_encode($company);

y por ultimo consulto de la siguiente forma: https://myhosting.com/api_ruc/directorio_subido/api.php.  pero no obtengo respuesta , como deberia consultar los datos luego de subir los archivos al hosting?

**Comment by elviss116** [comment]
ya logre hacerlo correr amigo, muchas gracias por todo, como la api del DNI ya se soluciono cerrare el issue
