### ISSUE TITLE
Desplegar el api en hosting 

### ISSUE THREAD

**Issue by washingtonaya** [giansalex/peru-consult-api#33]
Saludos estimado @giansalex . 
Estuve intentado desplegar el apli en mi cloud. pero no me funciona simplemente no agarra el index 
Hay alguna ruta que hay que cambiar para que pueda funcionar en la nube ya que local me funciona correctamente.

**Comment by giansalex** [comment]
Dependiendo del servidor web, para el caso de Apache, existe las reglas configuradas en [.htaccess](https://github.com/giansalex/peru-consult-api/blob/master/public/.htaccess)

**Comment by washingtonaya** [comment]
El servidor web es : Apache 2.4.51

**Comment by washingtonaya** [comment]
Para ser mas exacto estoy intentando desplegar en hosting de godaddy  en un subdominio.

**Comment by giansalex** [comment]
Deberias poder acceder desde `subdomain.example.com/public/`

**Comment by washingtonaya** [comment]
logre acceder pero ahora me sale este error
![image](https://user-images.githubusercontent.com/77364874/140426676-189e2266-f47e-4d78-b61d-07a442bc3095.png)

**Comment by giansalex** [comment]
Debe ser la version de PHP, se necesita PHP 7.4 o superior

**Comment by washingtonaya** [comment]
Gracias estimado @giansalex
