### ISSUE TITLE
No se pudo crear imagen desde el captcha

### ISSUE THREAD

**Issue by xMarcelo** [giansalex/peru-consult-api#9]
Hola,
Obtengo los siguientes mensajes al momento de consultar por DNI

Por el url:
public/api/v1/dni/48004836?token=abcxyz

>> mensaje : No se pudo crear imagen desde el captcha

curl -s http://docker/api/v1/dni/46658592?token=123456|json_pp

>> mensaje : no se pudo crear la imagen

Muchas gracias por su ayuda.

**Comment by giansalex** [comment]
El problema es que el servicio de Reniec esta caído.
Esto esta referenciado a https://github.com/giansalex/peru-consult/issues/10
